import Document, { Html, Head, Main, NextScript } from 'next/document'

class MyDocument extends Document {
    static async getInitialProps(ctx) {
        const initialProps = await Document.getInitialProps(ctx)
        return { ...initialProps }
    }
    render() {
        return (
            <Html>
                <Head>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                    <link
                        rel="preload" as="font"
                        href="../public/static/Fonts/Poppins/Poppins-Light.ttf"
                        crossOrigin=""/>
                    <link
                        rel="preload" as="font"
                        href="../public/static/Fonts/Nunito_Sans/NunitoSans-Light.ttf"
                        crossOrigin=""/>

                </Head>
                <body>
                <Main />
                <NextScript />
                </body>
            </Html>
        )
    }
}

export default MyDocument